// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZU6BfF9mA_1MQsyFcXYAowYEKKwTmtE',
    appId: '1:629869657780:android:a2e23041993cfbca7961e1',
    messagingSenderId: '629869657780',
    projectId: 'kma-app-5f04c',
    storageBucket: 'kma-app-5f04c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-scv5gWnWRpH8Ak3eVACs23uFCltGvZI',
    appId: '1:629869657780:ios:09f27f3d975665ff7961e1',
    messagingSenderId: '629869657780',
    projectId: 'kma-app-5f04c',
    storageBucket: 'kma-app-5f04c.appspot.com',
    iosBundleId: 'com.stylemixthemes.masterstudyapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinuAZDdCICKOZ_lEMUTmLjbgc5vNFnn4',
    appId: '1:629869657780:web:0ec6710c904a58397961e1',
    messagingSenderId: '629869657780',
    projectId: 'kma-app-5f04c',
    authDomain: 'kma-app-5f04c.firebaseapp.com',
    storageBucket: 'kma-app-5f04c.appspot.com',
    measurementId: 'G-93KFFFQ3WK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-UEs8cQpak7GheDv6KjVDW0E6Q2OQio',
    appId: '1:149451833753:ios:9c66f455f95510314c5308',
    messagingSenderId: '149451833753',
    projectId: 'kma-app-2fd07',
    storageBucket: 'kma-app-2fd07.appspot.com',
    iosBundleId: 'y',
  );

}