// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfwdKFCSS86UV4NAabUBoWrPzUNcgOik',
    appId: '1:149451833753:android:00246bc1515f40704c5308',
    messagingSenderId: '149451833753',
    projectId: 'kma-app-2fd07',
    storageBucket: 'kma-app-2fd07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-UEs8cQpak7GheDv6KjVDW0E6Q2OQio',
    appId: '1:149451833753:ios:d6c0d326f7df9db64c5308',
    messagingSenderId: '149451833753',
    projectId: 'kma-app-2fd07',
    storageBucket: 'kma-app-2fd07.appspot.com',
    iosBundleId: 'com.stylemixthemes.masterstudyapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ThJP3QdkMmGD9tmhQxkmFZ_Yei77aI0',
    appId: '1:149451833753:web:a7e7bcbf04f29b1f4c5308',
    messagingSenderId: '149451833753',
    projectId: 'kma-app-2fd07',
    authDomain: 'kma-app-2fd07.firebaseapp.com',
    storageBucket: 'kma-app-2fd07.appspot.com',
    measurementId: 'G-8LRXBQE0TT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-UEs8cQpak7GheDv6KjVDW0E6Q2OQio',
    appId: '1:149451833753:ios:9c66f455f95510314c5308',
    messagingSenderId: '149451833753',
    projectId: 'kma-app-2fd07',
    storageBucket: 'kma-app-2fd07.appspot.com',
    iosBundleId: 'y',
  );

}